import os

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ASTRA_DB_APPLICATION_TOKEN = os.getenv('ASTRA_DB_APPLICATION_TOKEN_VECTOR')
ASTRA_DB_API_ENDPOINT = os.getenv('ASTRA_DB_API_ENDPOINT')
ASTRA_DB_COLLECTION = os.getenv('ASTRA_DB_COLLECTION_DEV')